# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: host-pvc
# spec:
#   volumeName: host-pv
#   accessModes:
#     - ReadWriteOnce
#   storageClassName: standard
#   resources:
#     requests:
#       storage: 1Gi
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  # name: postgres-pv-claim
  name: host-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi