# apiVersion: policy/v1beta1
# kind: PodSecurityPolicy
# metadata:
#   name: example
# spec:
#   seLinux:
#     rule: RunAsAny
#   supplementalGroups:
#     rule: RunAsAny
#   runAsUser:
#     rule: RunAsAny
#   fsGroup:
#     rule: RunAsAny
#   volumes:
#   - '*'
#   privileged: false  # Don't allow privileged pods!
#   allowedHostPaths:
#   - pathPrefix: /fp_data
#     readOnly: false
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: privileged
  annotations:
    seccomp.security.alpha.kubernetes.io/allowedProfileNames: '*'
spec:
  privileged: true
  allowPrivilegeEscalation: true
  allowedCapabilities:
  - '*'
  volumes:
  - '*'
  hostNetwork: true
  hostPorts:
  - min: 0
    max: 65535
  hostIPC: true
  hostPID: true
  runAsUser:
    rule: 'RunAsAny'
  seLinux:
    rule: 'RunAsAny'
  supplementalGroups:
    rule: 'RunAsAny'
  fsGroup:
    rule: 'RunAsAny'