apiVersion: v1
kind: Service
metadata:
  name: backend
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  selector:
    app: backend
  ports:
    - protocol: "TCP"
      port: 5010
      targetPort: 5010
  type: LoadBalancer
